// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0mlxUy--XQpTWk00s8G356TByn96U6vc',
    appId: '1:638208033117:android:b4e35b246c6f72959a68b4',
    messagingSenderId: '638208033117',
    projectId: 'trash-detector-b0bd4',
    databaseURL:
        'https://trash-detector-b0bd4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trash-detector-b0bd4.firebasestorage.app',
  );
}
